<h1><b>MIT CSINÁLUNK MI?</b></h1>
<p>A Szülők Háza Alapítványt dr. Kemény Dénes hozta létre, azzal a céllal, hogy az alapítvány szervezeti formában képviselhesse tovább a 2007 óta működő Szülők Háza mozgalom elveit és céljait. 
A Regős Judit elnökasszony által vezetett Alapítvány a családdá alakulás kezdeti nehézségeiben segít, illetve nehéz helyzetben élő családoknak és családi támogatás nélkül, állami gondoskodásban élő gyerekeknek nyújt támogatást.
Az elsődleges célunk az, hogy elősegítsük a nehéz helyzetben élők integrációját, erősítsük a befogadására a többségi társadalmat.
A Tegyél jót! Ülj mellém! egy olyan komplex program, amely állami gondoskodásban élő gyerekek számára nyújt segítséget társadalmi integrációjukhoz. A kapcsolódó családok személyes történetei példát jelenthetnek, motivációt nyújthatnak a tanulásra, felkelthetik az állami gondoskodásban élő gyerekek igényét a minőségi életre.</p></>
<h2>A Szülők Háza Alapítvány</h2>
<p>A Szülők Háza Alapítványt Kemény Dénes hozta létre 2015-ben azzal a céllal, hogy az alapítvány szervezeti formában képviselhesse tovább a 2007 óta működő Szülők Háza mozgalom elveit és céljait. Az Alapítvány állami gondoskodásban élő gyerekek és hátrányos helyzetű családok számára nyújt támogatást.  Az elsődleges cél az, hogy elősegítse a rászorulók integrációját, ezzel is erősítve a kisebbség befogadására a többségi társadalmat. A Szülők Háza Alapítványnál azért dolgozunk, hogy reményt és lehetőségeket adjunk azoknak, akik nehéz körülmények közé születtek, élethelyzetük, esélyeik javuljanak és befogadóbb, megértőbb szemléletet alakítsunk ki a többségi társadalom tagjaiban.</p>
<h2>A Szülők Háza Alapítvány programjai</h2>
<p>A Szülők Háza Alapítvány programjai illeszkednek az önkormányzatok által nyújtott gyermekjóléti támogatásokhoz, a különböző hazai és uniós pályázatokhoz, illetve az üzleti szféra CSR programjaihoz. A központban szakemberek – családterapeuták, pszichológusok, pedagógusok – segítenek a szülőknek, de maga a szülői közösség is sokszor megoldást tud nyújtani egy-egy családnak.
A Szülők Háza Alapítvány családokat segítő programjaiban számos rászoruló család kap segítséget, akiket a speciális készségfejlesztő és sport, művészeti és közösségi programokon keresztül az „egészséges” családok körébe vonva a program hatékonyan képes segíteni.
A Tegyél jót! programunk célközönsége a gyermekotthonokban élő gyermekek. Magyarországon több száz gyermekotthon van, több ezer gyermek nevelkedik állami gondozottként nehéz körülmények között. Ezen program keretében rendszeres odafigyelést, törődést biztosítunk a gyerekeknek önkénteseink révén, a program célja tehát rendszeresen összehozni a segíteni vágyó családokat az állami gondozott gyerekekkel az Alapítvány szakmai támogatása mellett.</p>
<h2>Háttér</h2>
<p>A gyermekek a közösségi és társas szükségletek területén vannak leginkább kitéve a nélkülözésnek, megfosztottságnak. A gyermekek harmada (35%) nem tud elmenni nyaralni, míg 29%-uk esetében a szabadidős tevékenységekben való részvétel (sport, művészetek, közösségi játék, tehetséggondozás, stb.) is korlátozott. 2012-ben a Magyarországban élő gyermekek 46,5%-a nem engedhetett meg magának napi egyszeri hús, hal vagy azzal egyenértékű vegetáriánus étel fogyasztását. Száz szegénységben élő személy közül 34 gyermek vagy fiatal. A szegénység generációkon keresztül öröklődik.A sok gyermek szegénységi kockázatot jelent.</p>
<h2>Rászorultsági csapda</h2>
<p>A mai kor egyik nagy problémája a szeparálódás, melynek következménye, hogy a hátrányos helyzetű családok sokszor elzártan, saját közösségükben élnek, nincs módjuk kapcsolatokat teremteni, kitörni a rászorultsági csapdából. Az alapszükségletek megfelelő kielégítésének hiányán túl, gyakori jelenség, hogy ezen családokban felnevelkedő gyermekek nem férnek hozzá a sportolási, kulturális (színház, stb) lehetőségekhez sem. Az állami eszközrendszer szükséges, de többnyire nem elégséges forrása a családok kilábalásának ebből a nehéz helyzetből, a civil összefogásnak, a társadalmi felelősségvállalásnak is jelentős szerep jut.
A Szülők Háza tehát olyan közösségek létrejöttén dolgozik, mely teret ad a szociokulturális hátránnyal és a az előnyösebb háttérrel rendelkező családok találkozásának. Az itt megélt közösségi élmények fejlesztik a toleranciát, empátiás készséget, a hátrányos helyzetben élők pedig új ismereteket, megküzdési stratégiákat sajátíthatnak el, minőségi szolgáltatásokhoz férhetnek hozzá, kibővül szociális támogató rendszerük, és nem utolsó sorban kitörési lehetőséget biztosítanak számukra.</p>